name: 'Restore Built App'
description: 'Restore built Spartacus application from cache'
inputs:
  cache-key:
    description: 'Cache key for built app'
    required: true
  fail-on-cache-miss:
    description: 'Whether to fail if cache miss occurs'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Restore built app
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 #v4.3.0
      with:
        path: |
          dist/storefrontapp
        key: spartacus-app-${{ inputs.cache-key }}
        fail-on-cache-miss: ${{ inputs.fail-on-cache-miss }}
