name: 'Prevent Retries'
description: 'Forcefully fail build if job is retried'

runs:
  using: 'composite'
  steps:
    - name: Forcefully fail build if job is retried
      uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
      with:
        script: |
          core.setFailed('Please push a commit to trigger the build. To push an empty commit you can use `git commit --allow-empty -m "Trigger Build"`')
      if: ${{ github.run_attempt > 1 }}
