name: 'Prevent Retries'
description: 'Forcefully fail build if job is retried'

runs:
  using: 'composite'
  steps:
    - name: Forcefully fail build if job is retried
      uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b #v7.1.0
      with:
        script: |
          core.setFailed('Please push a commit to trigger the build. To push an empty commit you can use `git commit --allow-empty -m "Trigger Build"`')
      if: ${{ github.run_attempt > 1 }}
