import { SPARTACUS_PRODUCT_CONFIGURATOR } from '@spartacus/schematics';

export const PRODUCT_CONFIGURATOR_MODULE_NAME = 'ProductConfigurator';
export const PRODUCT_CONFIGURATOR_FOLDER_NAME = 'product-configurator';
export const PRODUCT_CONFIGURATOR_SCSS_FILE_NAME = 'product-configurator.scss';
export const PRODUCT_CONFIGURATOR_TRANSLATIONS = 'configuratorTranslations';
export const PRODUCT_CONFIGURATOR_TRANSLATION_CHUNKS_CONFIG =
  'configuratorTranslationChunksConfig';

export const PRODUCT_CONFIGURATOR_TEXTFIELD_MODULE_NAME =
  'ProductConfiguratorTextfield';
export const PRODUCT_CONFIGURATOR_TEXTFIELD_FEATURE_NAME_CONSTANT =
  'PRODUCT_CONFIGURATOR_TEXTFIELD_FEATURE';
export const PRODUCT_CONFIGURATOR_TEXTFIELD_MODULE =
  'TextfieldConfiguratorModule';
export const PRODUCT_CONFIGURATOR_TEXTFIELD_ROOT_MODULE =
  'TextfieldConfiguratorRootModule';
export const SPARTACUS_PRODUCT_CONFIGURATOR_TEXTFIELD =
  '@spartacus/product-configurator/textfield';
export const SPARTACUS_PRODUCT_CONFIGURATOR_TEXTFIELD_ROOT = `${SPARTACUS_PRODUCT_CONFIGURATOR_TEXTFIELD}/root`;

export const PRODUCT_CONFIGURATOR_RULEBASED_MODULE_NAME =
  'ProductConfiguratorRulebased';
export const PRODUCT_CONFIGURATOR_RULEBASED_FEATURE_NAME_CONSTANT =
  'PRODUCT_CONFIGURATOR_RULEBASED_FEATURE';
export const PRODUCT_CONFIGURATOR_RULEBASED_MODULE =
  'RulebasedConfiguratorModule';
export const PRODUCT_CONFIGURATOR_RULEBASED_ROOT_MODULE =
  'RulebasedConfiguratorRootModule';
export const PRODUCT_CONFIGURATOR_RULEBASED_CPQ_MODULE =
  'RulebasedCpqConfiguratorModule';
export const PRODUCT_CONFIGURATOR_RULEBASED_CPQ_ROOT_MODULE =
  'CpqConfiguratorRootModule';
export const SPARTACUS_PRODUCT_CONFIGURATOR_RULEBASED =
  '@spartacus/product-configurator/rulebased';
export const SPARTACUS_PRODUCT_CONFIGURATOR_RULEBASED_ROOT = `${SPARTACUS_PRODUCT_CONFIGURATOR_RULEBASED}/root`;
export const SPARTACUS_PRODUCT_CONFIGURATOR_ASSETS = `${SPARTACUS_PRODUCT_CONFIGURATOR}/common/assets`;
export const SPARTACUS_PRODUCT_CONFIGURATOR_RULEBASED_CPQ = `${SPARTACUS_PRODUCT_CONFIGURATOR_RULEBASED}/cpq`;
