import 'cypress-testing-library/add-commands';
import './ng-select.commands';
import './select-user-menu-option.commands';
import './require-logged-in.commands';
import './require-product-added-to-cart.commands';
import './require-shipping-address-added.commands';
import './require-shipping-method-selected.commands';
import './require-payment-done.commands';
import './login.commands';
