export enum OrganizationTableType {
  COST_CENTER = 'costCenter',
  COST_CENTER_BUDGETS = 'costCenterBudgets',
  COST_CENTER_ASSIGN_BUDGET = 'costCenterAssignBudgets',
  USER_GROUP = 'userGroup',
  USER_GROUP_USERS = 'userGroupUsers',
  USER_GROUP_ASSIGN_USER = 'userGroupAssignUsers',
  USER_GROUP_PERMISSIONS = 'userGroupPermissions',
  USER_GROUP_ASSIGN_PERMISSIONS = 'userGroupAssignPermissions',
  USER = 'user',
  USER_APPROVERS = 'userApprovers',
  USER_ASSIGN_APPROVERS = 'userAssignApprovers',
  USER_PERMISSIONS = 'userPermissions',
  USER_ASSIGN_PERMISSIONS = 'userAssignPermissions',
  USER_USER_GROUPS = 'userUserGroups',
  USER_ASSIGN_USER_GROUPS = 'userAssignUserGroups',
}
