name: 'Setup Node and Cache'
description: 'Setup Node.js and cache node_modules and Cypress cache'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '20'
  cache-key:
    description: 'Base cache key'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 #v4.4.0
      with:
        node-version: ${{ inputs.node-version }}

    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: |
          node_modules
          projects/storefrontapp-e2e-cypress/node_modules
          ~/.cache/Cypress
        key: nodemodules-${{ inputs.cache-key }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: nodemodules-${{ inputs.cache-key }}-

    - name: Package installation
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci
