import {
  AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  ComponentRef,
  ElementRef,
  Input,
  OnDestroy,
  OnInit,
  Renderer2,
  TemplateRef,
} from '@angular/core';
import { WindowRef } from '@spartacus/core';
import { Subscription } from 'rxjs';
import { PopoverPosition } from './popover.model';
import { PositioningService } from './positioning.service';

@Component({
  selector: 'cx-popover',
  templateUrl: './popover.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PopoverComponent implements OnInit, AfterViewInit, OnDestroy {
  /**
   * String or template to be rendered inside popover wrapper component.
   */
  @Input() content: string | TemplateRef<any>;

  /**
   * Element which triggers displaying popover component.
   * This property is needed to calculate valid position for popover.
   */
  @Input() triggerElement: ElementRef;

  /**
   * Current initiated popover instance.
   */
  @Input() popoverInstance: ComponentRef<PopoverComponent>;

  /**
   * Flag which informs positioning service if popover component
   * should be appended to body. Otherwise popover is displayed right after
   * trigger element in DOM.
   */
  @Input() appendToBody?: boolean;

  /**
   * The preferred placement of the popover. Default popover position is 'auto'.
   */
  @Input() position?: PopoverPosition;

  /**
   * Flag which indicates if passed content is a TemplateRef or string.
   */
  isTemplate: boolean;

  /**
   * After popover component is initialized position needs to be changing dynamically
   * in case if any viewport changes happen.
   */
  resizeSub: Subscription;

  /**
   * Class name generated by positioning service indicating position of popover.
   */
  popoverClass: string;

  ngOnInit(): void {
    this.isTemplate = this.content instanceof TemplateRef;
  }

  ngAfterViewInit(): void {
    this.resizeSub = this.winRef.resize$.subscribe(() => {
      this.popoverClass = this.positioningService.positionElements(
        this.triggerElement.nativeElement,
        this.popoverInstance.location.nativeElement,
        this.position,
        this.appendToBody
      );
      this.renderer.removeAttribute(
        this.popoverInstance.location.nativeElement,
        'class'
      );
      this.renderer.addClass(
        this.popoverInstance.location.nativeElement,
        this.popoverClass
      );
    });
  }

  ngOnDestroy(): void {
    if (this.resizeSub) {
      this.resizeSub.unsubscribe();
    }
  }

  constructor(
    protected positioningService: PositioningService,
    protected winRef: WindowRef,
    protected renderer: Renderer2
  ) {}
}
