/*
 * SPDX-FileCopyrightText: 2026 SAP Spartacus team <spartacus-team@sap.com>
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Checks that whenever a `package.json` file is modified, the `package-lock.json`
 * file living in the same directory is updated as well.
 *
 * This is verified for every directory in the repository that has both a
 * `package.json` and a `package-lock.json` file.
 */

import { existsSync } from 'fs';
import { globSync } from 'glob';
import * as path from 'path';
import { chalk } from '../chalk';
import { PACKAGE_JSON } from './const';
import { ProgramOptions, error, reportProgress, success } from './index';

const PACKAGE_LOCK_JSON = 'package-lock.json';

/**
 * Read the list of files changed by the pull request, provided by the CI
 * workflow through the `CHANGED_FILES` environment variable (one path per line).
 *
 * Returns `undefined` when the variable is not set, so the caller can skip.
 */
function getChangedFiles(): string[] | undefined {
  const changedFiles = process.env.CHANGED_FILES;
  if (changedFiles === undefined) {
    return undefined;
  }

  return changedFiles
    .split('\n')
    .map((file) => file.trim())
    .filter(Boolean);
}

/**
 * Normalize a path to use forward slashes for cross-platform comparison.
 *
 * @param filePath path to normalize
 */
function toPosix(filePath: string): string {
  return filePath.split(path.sep).join('/');
}

/**
 * Verify that every modified `package.json` has its sibling `package-lock.json`
 * updated as well.
 *
 * @param options script options
 */
export function checkLockFiles(options: ProgramOptions): void {
  // In fix mode the root lock file is regenerated by `npm install` later.
  if (options.fix) {
    return;
  }

  reportProgress(
    `Checking that modified \`${PACKAGE_JSON}\` files have an updated \`${PACKAGE_LOCK_JSON}\``
  );

  const changedFiles = getChangedFiles();
  if (changedFiles === undefined) {
    success(' ✔  Skipped (no list of changed files provided)');
    return;
  }

  const changed = new Set(changedFiles.map(toPosix));

  // Every directory that has a lock file (and thus a sibling `package.json`).
  const lockFilePaths = globSync(`**/${PACKAGE_LOCK_JSON}`, {
    ignore: ['**/node_modules/**'],
    dot: true,
  }).map(toPosix);

  let violations = 0;

  lockFilePaths.forEach((lockPath) => {
    const directory =
      lockPath.substring(0, lockPath.length - `/${PACKAGE_LOCK_JSON}`.length) ||
      '.';
    const packageJsonPath =
      directory === '.' ? PACKAGE_JSON : `${directory}/${PACKAGE_JSON}`;

    // A lock file without its `package.json` sibling is not something we check.
    if (!existsSync(packageJsonPath)) {
      return;
    }

    const packageJsonChanged = changed.has(packageJsonPath);
    const lockChanged = changed.has(lockPath);

    if (packageJsonChanged && !lockChanged) {
      violations++;
      error(
        packageJsonPath,
        [
          `\`${packageJsonPath}\` was modified but \`${lockPath}\` was not updated.`,
        ],
        [
          `Run \`${chalk.bold('npm install')}\`${
            directory === '.' ? '' : ` in \`${directory}\``
          } to regenerate the lock file,`,
          `then commit the updated \`${lockPath}\`.`,
        ]
      );
    }
  });

  if (violations === 0) {
    success();
  }
}
