/*
 * SPDX-FileCopyrightText: 2026 SAP Spartacus team <spartacus-team@sap.com>
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Checks that whenever a `package.json` file is modified, the `package-lock.json`
 * file living in the same directory is updated as well.
 *
 * This is verified for every directory in the repository that has both a
 * `package.json` and a `package-lock.json` file.
 */

import { execSync } from 'child_process';
import { existsSync, readFileSync } from 'fs';
import { globSync } from 'glob';
import * as path from 'path';
import { chalk } from '../chalk';
import { PACKAGE_JSON } from './const';
import { ProgramOptions, error, reportProgress, success } from './index';

const PACKAGE_LOCK_JSON = 'package-lock.json';

/**
 * Fields of a `package.json` that influence the resolved dependency tree and
 * therefore the `package-lock.json`. Changes to any other field (e.g.
 * `scripts`, `description`, tooling config) do not require a lock file update.
 */
const DEPENDENCY_FIELDS = [
  'dependencies',
  'devDependencies',
  'optionalDependencies',
  'peerDependencies',
  'peerDependenciesMeta',
  'bundleDependencies',
  'bundledDependencies',
  'overrides',
  'workspaces',
] as const;

/**
 * Read the list of files changed by the pull request, provided by the CI
 * workflow through the `CHANGED_FILES` environment variable (one path per line).
 *
 * Returns `undefined` when the variable is not set, so the caller can skip.
 */
function getChangedFiles(): string[] | undefined {
  const changedFiles = process.env.CHANGED_FILES;
  if (changedFiles === undefined) {
    return undefined;
  }

  return changedFiles
    .split('\n')
    .map((file) => file.trim())
    .filter(Boolean);
}

/**
 * Normalize a path to use forward slashes for cross-platform comparison.
 *
 * @param filePath path to normalize
 */
function toPosix(filePath: string): string {
  return filePath.split(path.sep).join('/');
}

/**
 * Extract only the dependency-relevant fields from a `package.json`, so two
 * revisions can be compared while ignoring unrelated changes (scripts,
 * description, tooling config, ...).
 *
 * @param content parsed `package.json` content
 */
function pickDependencyFields(content: Record<string, unknown>): string {
  const relevant: Record<string, unknown> = {};
  for (const field of DEPENDENCY_FIELDS) {
    if (content[field] !== undefined) {
      relevant[field] = content[field];
    }
  }
  return JSON.stringify(relevant);
}

/**
 * Return the content of a file at a given git revision, or `undefined` when it
 * cannot be read (e.g. the file did not exist at that revision, or the revision
 * is not available locally).
 *
 * @param revision git revision (branch, tag or SHA)
 * @param filePath repository-relative file path
 */
function readFileAtRevision(
  revision: string,
  filePath: string
): string | undefined {
  try {
    return execSync(`git show ${revision}:${filePath}`, {
      encoding: 'utf-8',
      stdio: ['ignore', 'pipe', 'ignore'],
    });
  } catch {
    return undefined;
  }
}

/**
 * Determine whether the dependency-relevant fields of a `package.json` changed
 * between the base revision and the working tree.
 *
 * When the base revision is unavailable (not fetched, or the file is new) we
 * conservatively assume the dependencies changed, so the lock file check still
 * applies.
 *
 * @param packageJsonPath repository-relative path to the `package.json`
 * @param baseRevision base git revision to compare against
 */
function dependenciesChanged(
  packageJsonPath: string,
  baseRevision: string
): boolean {
  const baseContent = readFileAtRevision(baseRevision, packageJsonPath);
  if (baseContent === undefined) {
    return true;
  }

  try {
    const base = pickDependencyFields(JSON.parse(baseContent));
    const current = pickDependencyFields(
      JSON.parse(readFileSync(packageJsonPath, 'utf-8'))
    );
    return base !== current;
  } catch {
    return true;
  }
}

/**
 * Verify that every modified `package.json` has its sibling `package-lock.json`
 * updated as well.
 *
 * @param options script options
 */
export function checkLockFiles(options: ProgramOptions): void {
  // In fix mode the root lock file is regenerated by `npm install` later.
  if (options.fix) {
    return;
  }

  reportProgress(
    `Checking that modified \`${PACKAGE_JSON}\` files have an updated \`${PACKAGE_LOCK_JSON}\``
  );

  const changedFiles = getChangedFiles();
  if (changedFiles === undefined) {
    success(' ✔  Skipped (no list of changed files provided)');
    return;
  }

  const changed = new Set(changedFiles.map(toPosix));

  // Base revision to diff against, so we only flag changes that actually affect
  // the dependency tree. When it is not provided we fall back to flagging any
  // `package.json` change (previous, path-only behaviour).
  const baseRevision = process.env.BASE_REF?.trim();

  // Every directory that has a lock file (and thus a sibling `package.json`).
  const lockFilePaths = globSync(`**/${PACKAGE_LOCK_JSON}`, {
    ignore: ['**/node_modules/**'],
    dot: true,
  }).map(toPosix);

  let hasViolations = false;

  lockFilePaths.forEach((lockPath) => {
    const directory =
      lockPath.substring(0, lockPath.length - `/${PACKAGE_LOCK_JSON}`.length) ||
      '.';
    const packageJsonPath =
      directory === '.' ? PACKAGE_JSON : `${directory}/${PACKAGE_JSON}`;

    // A lock file without its `package.json` sibling is not something we check.
    if (!existsSync(packageJsonPath)) {
      return;
    }

    const packageJsonChanged = changed.has(packageJsonPath);
    const lockChanged = changed.has(lockPath);

    if (!packageJsonChanged || lockChanged) {
      return;
    }

    // `package.json` changed without a lock update: only a real problem when
    // the dependency-relevant fields are what changed.
    if (baseRevision && !dependenciesChanged(packageJsonPath, baseRevision)) {
      return;
    }

    hasViolations = true;
    error(
      packageJsonPath,
      [
        `\`${packageJsonPath}\` was modified but \`${lockPath}\` was not updated.`,
      ],
      [
        `Run \`${chalk.bold('npm install')}\`${
          directory === '.' ? '' : ` in \`${directory}\``
        } to regenerate the lock file,`,
        `then commit the updated \`${lockPath}\`.`,
      ]
    );
  });

  if (!hasViolations) {
    success();
  }
}
