/*
 * SPDX-FileCopyrightText: 2026 SAP Spartacus team <spartacus-team@sap.com>
 *
 * SPDX-License-Identifier: Apache-2.0
 */

import { TestBed } from '@angular/core/testing';
// eslint-disable-next-line @nx/workspace-no-self-public-api-import -- ESLint is misfiring here: core and root are not the same library — they're separate entry points
import { OrderEntry } from '@spartacus/cart/base/root';
import {
  SiteContextParamsService,
  StatePersistenceService,
  WindowRef,
} from '@spartacus/core';
import { of, Subject } from 'rxjs';
import { ActiveCartStatePersistenceService } from './active-cart-state-persistence.service';
import { vi } from 'vitest';

const BASE_SITE = 'electronics-spa';

const store: Record<string, string | undefined> = {};
const MockWindowRef = {
  localStorage: {
    getItem: (key: string): string | null =>
      key in store ? (store[key] as string) : null,
    setItem: (key: string, value: string) => {
      store[key] = `${value}`;
    },
    removeItem: (key: string): void => {
      delete store[key];
    },
  },
  isBrowser: (): boolean => true,
};

const mockCartEntry: OrderEntry = {
  entryNumber: 0,
  product: { code: 'code' },
  quantity: 1,
};

describe('ActiveCartStatePersistenceService', () => {
  let service: ActiveCartStatePersistenceService;
  let winRef: WindowRef;
  // Full storage key as generated by StatePersistenceService for the base-site
  // context (spartacus⚿<baseSite>⚿<key>).
  let STORAGE_KEY: string;

  beforeEach(() => {
    for (const key of Object.keys(store)) {
      delete store[key];
    }

    TestBed.configureTestingModule({
      providers: [
        ActiveCartStatePersistenceService,
        StatePersistenceService,
        { provide: WindowRef, useValue: MockWindowRef },
        {
          provide: SiteContextParamsService,
          useValue: { getValues: () => of([BASE_SITE]) },
        },
      ],
    });

    service = TestBed.inject(ActiveCartStatePersistenceService);
    winRef = TestBed.inject(WindowRef);
    STORAGE_KEY = `spartacus⚿${BASE_SITE}⚿${service['key']}`;
  });

  it('should be created', () => {
    expect(service).toBeTruthy();
  });

  describe('initSync', () => {
    it('should persist normalized entries under the base-site context', () => {
      const entries$ = new Subject<OrderEntry[]>();

      service.initSync(entries$);
      entries$.next([mockCartEntry]);

      expect(winRef.localStorage?.getItem(STORAGE_KEY)).toEqual(
        JSON.stringify([{ product: { code: 'code' }, quantity: 1 }])
      );
    });

    it('should drop entries without a product code or quantity', () => {
      const entries$ = new Subject<OrderEntry[]>();

      service.initSync(entries$);
      entries$.next([
        { product: {}, quantity: 1 },
        { product: { code: 'code' }, quantity: 0 },
      ]);

      expect(winRef.localStorage?.getItem(STORAGE_KEY)).toEqual(
        JSON.stringify([])
      );
    });

    it('should stop persisting once unsubscribed on destroy', () => {
      const entries$ = new Subject<OrderEntry[]>();

      service.initSync(entries$);
      service.ngOnDestroy();
      entries$.next([mockCartEntry]);

      expect(winRef.localStorage?.getItem(STORAGE_KEY)).toBeFalsy();
    });
  });

  describe('readGuestCartState', () => {
    it('should read persisted entries', () => {
      const persisted = [{ product: { code: 'code' }, quantity: 1 }];
      winRef.localStorage?.setItem(STORAGE_KEY, JSON.stringify(persisted));

      expect(service.readGuestCartState()).toEqual(persisted as OrderEntry[]);
    });

    it('should return undefined when nothing is persisted', () => {
      expect(service.readGuestCartState()).toBeUndefined();
    });

    it('should return undefined when an empty list is persisted', () => {
      winRef.localStorage?.setItem(STORAGE_KEY, JSON.stringify([]));

      expect(service.readGuestCartState()).toBeUndefined();
    });
  });

  describe('clearGuestCartState', () => {
    it('should remove the storage entry entirely rather than leaving an empty value', () => {
      vi.spyOn(winRef.localStorage as Storage, 'removeItem');
      winRef.localStorage?.setItem(
        STORAGE_KEY,
        JSON.stringify([{ product: { code: 'code' }, quantity: 1 }])
      );

      service.clearGuestCartState();

      expect(winRef.localStorage?.removeItem).toHaveBeenCalledWith(STORAGE_KEY);
      expect(winRef.localStorage?.getItem(STORAGE_KEY)).toBeFalsy();
    });
  });
});
