/*
 * SPDX-FileCopyrightText: 2026 SAP Spartacus team <spartacus-team@sap.com>
 *
 * SPDX-License-Identifier: Apache-2.0
 */

import { Express } from 'express';
import {
  SITEMAP_SHARED_STATE,
  waitForSitemapReady,
} from '../ssr-bridge/sitemap-shared-state';

/**
 * Options for sitemap serving middleware.
 */
export interface SitemapServingOptions {
  /**
   * URL path prefix for individual sitemap files (default: '/sitemaps')
   */
  servePath?: string;

  /**
   * Timeout for waiting for sitemap generation on first request (default: 60000ms)
   */
  timeout?: number;

  /**
   * If true, the middleware will trigger a warmup SSR request to itself
   * when sitemap is requested but Angular hasn't bootstrapped yet.
   * This ensures sitemaps are generated even if /sitemap.xml is the first request.
   * Default: true
   */
  enableSelfWarmup?: boolean;
}

/**
 * Sets up Express routes to serve sitemaps generated by Angular SSR.
 *
 * This middleware does NOT generate sitemaps — it only serves them.
 * Sitemap generation happens in Angular SSR context via `provideSitemapGenerator()`.
 *
 * The middleware serves sitemap XML content directly from in-memory shared state.
 * No files are written to disk.
 *
 * ## Usage
 *
 * ```typescript
 * // server.ts
 * import { setupSitemapServing } from '@spartacus/setup/sitemaps';
 *
 * const server = express();
 * setupSitemapServing(server);
 * ```
 *
 * ## How it works
 *
 * 1. Angular SSR generates sitemaps during bootstrap (via provideSitemapGenerator)
 * 2. Generated XML content is stored in SITEMAP_SHARED_STATE (Node.js memory)
 * 3. This middleware serves content from shared state on /sitemap.xml and /sitemaps/*.xml
 * 4. If sitemaps aren't ready yet, waits up to `timeout` ms
 */
export function setupSitemapServing(
  app: Express,
  options: SitemapServingOptions = {}
): void {
  const servePath = options.servePath || '/sitemaps';
  const timeout = options.timeout || 60000;
  const enableSelfWarmup = options.enableSelfWarmup ?? true;

  // Track if warmup has been triggered
  let warmupTriggered = false;

  console.log('[Sitemap] Serving middleware configured');

  /**
   * Triggers a self-warmup request to bootstrap Angular SSR.
   * This is needed when /sitemap.xml is the first request to the server.
   */
  function triggerWarmup(req: any): void {
    if (warmupTriggered || !enableSelfWarmup) return;
    warmupTriggered = true;

    const protocol = req.protocol || 'http';
    const host = req.get('host') || 'localhost:4000';
    const warmupUrl = `${protocol}://${host}/`;

    console.log(`[Sitemap] Triggering warmup request to ${warmupUrl} to bootstrap Angular SSR...`);

    // Use fetch to trigger an SSR render, which will bootstrap Angular
    // and generate sitemaps via APP_INITIALIZER
    fetch(warmupUrl, {
      headers: { 'User-Agent': 'SitemapWarmup/1.0' },
      // Allow self-signed certs for localhost
      ...(protocol === 'https' ? { rejectUnauthorized: false } as any : {}),
    }).catch(err => {
      console.warn(`[Sitemap] Warmup request failed (this is expected for self-signed certs): ${err.message}`);
    });
  }

  // Status endpoint
  app.get('/sitemap-status', (_req, res) => {
    res.json({
      isReady: SITEMAP_SHARED_STATE.isReady,
      isGenerating: SITEMAP_SHARED_STATE.isGenerating,
      lastUpdated: SITEMAP_SHARED_STATE.lastUpdated,
      files: SITEMAP_SHARED_STATE.sitemapFiles,
      totalUrls: SITEMAP_SHARED_STATE.totalUrls,
      urlsByLanguage: SITEMAP_SHARED_STATE.urlsByLanguage,
      error: SITEMAP_SHARED_STATE.error,
    });
  });

  // Main /sitemap.xml endpoint
  app.get('/sitemap.xml', async (req, res) => {
    // If sitemaps aren't ready, trigger a warmup SSR render
    if (!SITEMAP_SHARED_STATE.isReady && !SITEMAP_SHARED_STATE.isGenerating) {
      triggerWarmup(req);
    }

    try {
      const state = await waitForSitemapReady(timeout);
      const xml = state.sitemaps['sitemap.xml'];

      if (xml) {
        res.setHeader('Content-Type', 'application/xml; charset=utf-8');
        res.send(xml);
      } else {
        res.status(404).send('Sitemap index not available');
      }
    } catch (error) {
      const msg = error instanceof Error ? error.message : 'Unknown error';
      console.error('[Sitemap] Error serving sitemap.xml:', msg);
      res.status(503).setHeader('Content-Type', 'application/xml; charset=utf-8');
      res.send(`<?xml version="1.0" encoding="UTF-8"?>
<!-- Sitemap generation pending or failed: ${msg} -->
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
</sitemapindex>`);
    }
  });

  // Individual sitemap files: /sitemaps/sitemap-products-en.xml
  app.get(`${servePath}/:filename`, async (req, res) => {
    const filename = req.params['filename'];

    // If sitemaps aren't ready, trigger a warmup SSR render
    if (!SITEMAP_SHARED_STATE.isReady && !SITEMAP_SHARED_STATE.isGenerating) {
      triggerWarmup(req);
    }

    try {
      const state = await waitForSitemapReady(timeout);
      const xml = state.sitemaps[filename];

      if (xml) {
        res.setHeader('Content-Type', 'application/xml; charset=utf-8');
        res.send(xml);
      } else {
        res.status(404).send(`Sitemap file '${filename}' not found. Available: ${state.sitemapFiles.join(', ')}`);
      }
    } catch (error) {
      const msg = error instanceof Error ? error.message : 'Unknown error';
      res.status(503).send(`Sitemap not ready: ${msg}`);
    }
  });
}

// ---- Backward compatibility aliases ----

/**
 * @deprecated Use `setupSitemapServing()` instead.
 * Options are now split: generation config goes to `provideSitemapGenerator()`,
 * serving config goes to `setupSitemapServing()`.
 */
export interface SsrBridgeSitemapOptions {
  baseUrl: string;
  occBaseUrl: string;
  baseSiteId: string;
  outputDir: string;
  servePath?: string;
  configTimeout?: number;
  generateOnFirstRequest?: boolean;
  maxPageSize?: number;
  currency?: string;
}

/**
 * @deprecated Use `setupSitemapServing()` and `provideSitemapGenerator()` instead.
 *
 * This function now only sets up serving.
 * Generation config (baseUrl, occBaseUrl) should be passed to `provideSitemapGenerator()`
 * in app.config.server.ts.
 */
export function setupSsrBridgeSitemaps(
  app: Express,
  options: SsrBridgeSitemapOptions
): void {
  console.warn(
    '[Sitemap] setupSsrBridgeSitemaps() is deprecated. ' +
    'Use setupSitemapServing() in server.ts and provideSitemapGenerator() in app.config.server.ts instead.'
  );
  setupSitemapServing(app, {
    servePath: options.servePath,
    timeout: options.configTimeout,
  });
}
