export enum OrderDetailsSource {
  ORDER_APPROVAL = 'ORDER_APPROVAL',
  ORDER_CONFIRMATION = 'ORDER_CONFIRMATION',
  ORDER_DETAILS = 'ORDER_DETAILS',
  REPLENISHMENT_ORDER_DETAILS = 'REPLENISHMENT_ORDER_DETAILS',
}
