import { SPARTACUS_ORGANIZATION } from '@spartacus/schematics';

export const ORGANIZATION_FOLDER_NAME = 'organization';
export const SCSS_FILE_NAME = 'organization.scss';

export const ORGANIZATION_ADMINISTRATION_MODULE_NAME =
  'OrganizationAdministration';
export const ORGANIZATION_ADMINISTRATION_FEATURE_NAME_CONSTANT =
  'ORGANIZATION_ADMINISTRATION_FEATURE';
export const SPARTACUS_ADMINISTRATION = `${SPARTACUS_ORGANIZATION}/administration`;
export const SPARTACUS_ADMINISTRATION_ROOT = `${SPARTACUS_ADMINISTRATION}/root`;
export const SPARTACUS_ADMINISTRATION_ASSETS = `${SPARTACUS_ADMINISTRATION}/assets`;
export const ORGANIZATION_TRANSLATIONS = 'organizationTranslations';
export const ORGANIZATION_TRANSLATION_CHUNKS_CONFIG =
  'organizationTranslationChunksConfig';

export const ORGANIZATION_ORDER_APPROVAL_MODULE_NAME =
  'OrganizationOrderApproval';
export const ORGANIZATION_ORDER_APPROVAL_FEATURE_NAME_CONSTANT =
  'ORGANIZATION_ORDER_APPROVAL_FEATURE';
export const SPARTACUS_ORDER_APPROVAL = `${SPARTACUS_ORGANIZATION}/order-approval`;
export const SPARTACUS_ORDER_APPROVAL_ROOT = `${SPARTACUS_ORDER_APPROVAL}/root`;
export const SPARTACUS_ORDER_APPROVAL_ASSETS = `${SPARTACUS_ORDER_APPROVAL}/assets`;
export const ORDER_APPROVAL_TRANSLATIONS = 'orderApprovalTranslations';
export const ORDER_APPROVAL_TRANSLATION_CHUNKS_CONFIG =
  'orderApprovalTranslationChunksConfig';

export const ORGANIZATION_USER_REGISTRATION_MODULE_NAME =
  'OrganizationUserRegistration';
export const ORGANIZATION_USER_REGISTRATION_FEATURE_NAME_CONSTANT =
  'ORGANIZATION_USER_REGISTRATION_FEATURE';
export const SPARTACUS_USER_REGISTRATION = `${SPARTACUS_ORGANIZATION}/user-registration`;
export const SPARTACUS_USER_REGISTRATION_ROOT = `${SPARTACUS_USER_REGISTRATION}/root`;
export const SPARTACUS_USER_REGISTRATION_ASSETS = `${SPARTACUS_USER_REGISTRATION}/assets`;
export const USER_REGISTRATION_TRANSLATIONS =
  'organizationUserRegistrationTranslations';
export const USER_REGISTRATION_TRANSLATION_CHUNKS_CONFIG =
  'organizationUserRegistrationTranslationChunksConfig';
