// Mocked OCC payment details response for testing
import { PaymentDetails } from '../../../model/payment.model';

export const MOCK_PAYMENT_DETAILS: PaymentDetails[] = [
  {
    id: 'string',
    accountHolderName: 'Diksha Mocked Data',
    cardType: { code: 'string', name: 'string' },
    cardNumber: '4*** **** **** 1111',
    startMonth: '03',
    startYear: '2023',
    expiryMonth: '03',
    expiryYear: '2030',
    issueNumber: 'string',
    subscriptionId: 'string',
    saved: true,
    defaultPayment: true,
    billingAddress: {
      id: 'string',
      title: 'Mr.',
      titleCode: 'MR',
      firstName: 'John',
      lastName: 'Doe',
      companyName: 'Global Corp.',
      line1: '123 Main Street',
      line2: 'Garden Level',
      town: 'New York City',
      region: {
        isocode: 'US-NY',
        isocodeShort: 'NY',
        countryIso: 'US',
        name: 'New York',
      },
      district: '8th',
      postalCode: '10001',
      phone: '+1 (123) 456-7890',
      cellphone: '+1 (123) 456-7890',
      email: 'johndoe@domain.com',
      country: {
        isocode: 'US',
        name: 'United States',
      },
      shippingAddress: true,
      defaultAddress: true,
      visibleInAddressBook: true,
      formattedAddress: 'string',
    },
    sapPaymentMethod: {
      code: 'CreditCard',
      name: 'Credit Card',
    },
  },

  {
    id: 'string',
    accountHolderName: 'Diksha Mocked Data 2',
    cardType: { code: 'string', name: 'string' },
    cardNumber: '**** **** **** 1341',
    startMonth: '03',
    startYear: '2023',
    expiryMonth: '03',
    expiryYear: '2039',
    issueNumber: 'string',
    subscriptionId: 'string',
    saved: true,
    defaultPayment: true,
    billingAddress: {
      id: 'string',
      title: 'Mr.',
      titleCode: 'MR',
      firstName: 'John',
      lastName: 'Doe',
      companyName: 'Global Corp.',
      line1: '123 Main Street',
      line2: 'Garden Level',
      town: 'New York City',
      region: {
        isocode: 'US-NY',
        isocodeShort: 'NY',
        countryIso: 'US',
        name: 'New York',
      },
      district: '8th',
      postalCode: '10001',
      phone: '+1 (123) 456-7890',
      cellphone: '+1 (123) 456-7890',
      email: 'johndoe@domain.com',
      country: {
        isocode: 'US',
        name: 'United States',
      },
      shippingAddress: true,
      defaultAddress: true,
      visibleInAddressBook: true,
      formattedAddress: 'string',
    },
    sapPaymentMethod: {
      code: 'CreditCard',
      name: 'Credit Card',
    },
  },

  {
    id: 'string',
    accountHolderName: 'Mocked Data 3',
    cardType: { code: 'string', name: 'string' },
    cardNumber: '**** **** **** 1891',
    startMonth: '03',
    startYear: '2023',
    expiryMonth: '03',
    expiryYear: '2039',
    issueNumber: 'string',
    subscriptionId: 'string',
    saved: true,
    defaultPayment: true,
    billingAddress: {
      id: 'string',
      title: 'Mr.',
      titleCode: 'MR',
      firstName: 'John',
      lastName: 'Doe',
      companyName: 'Global Corp.',
      line1: '123 Main Street',
      line2: 'Garden Level',
      town: 'New York City',
      region: {
        isocode: 'US-NY',
        isocodeShort: 'NY',
        countryIso: 'US',
        name: 'New York',
      },
      district: '8th',
      postalCode: '10001',
      phone: '+1 (123) 456-7890',
      cellphone: '+1 (123) 456-7890',
      email: 'johndoe@domain.com',
      country: {
        isocode: 'US',
        name: 'United States',
      },
      shippingAddress: true,
      defaultAddress: true,
      visibleInAddressBook: true,
      formattedAddress: 'string',
    },
    sapPaymentMethod: {
      code: 'CreditCard',
      name: 'Credit Card',
    },
  },

  {
    id: 'string',
    accountHolderName: 'Mocked Data 4',
    cardType: { code: 'string', name: 'string' },
    cardNumber: '**** **** **** 0991',
    startMonth: '03',
    startYear: '2023',
    expiryMonth: '03',
    expiryYear: '2039',
    issueNumber: 'string',
    subscriptionId: 'string',
    saved: true,
    defaultPayment: true,
    billingAddress: {
      id: 'string',
      title: 'Mr.',
      titleCode: 'MR',
      firstName: 'John',
      lastName: 'Doe',
      companyName: 'Global Corp.',
      line1: '123 Main Street',
      line2: 'Garden Level',
      town: 'New York City',
      region: {
        isocode: 'US-NY',
        isocodeShort: 'NY',
        countryIso: 'US',
        name: 'New York',
      },
      district: '8th',
      postalCode: '10001',
      phone: '+1 (123) 456-7890',
      cellphone: '+1 (123) 456-7890',
      email: 'johndoe@domain.com',
      country: {
        isocode: 'US',
        name: 'United States',
      },
      shippingAddress: true,
      defaultAddress: true,
      visibleInAddressBook: true,
      formattedAddress: 'string',
    },
    sapPaymentMethod: {
      code: 'CreditCard',
      name: 'Credit Card',
    },
  },
];
