export * from './change-password-form/index';
export * from './change-password/index';
export * from './details/index';
export * from './form/index';
// export * from './permissions/assign/index';
// export * from './permissions/list/index';
export * from './services/index';
export * from './user-components.module';
// export * from './user-groups/assign/index';
// export * from './user-groups/list/index';
