export * from './carousel/product-carousel/product-carousel.component';
export * from './carousel/product-carousel/product-carousel.module';
export * from './carousel/product-references/product-references.component';
export * from './carousel/product-references/product-references.module';
export * from './current-product.service';
export * from './product-details/index';
export * from './product-list/index';
export * from './product-outlets.model';
export * from './product-tabs/index';
