export enum ProductDetailOutlets {
  SUMMARY = 'PDP.SUMMARY',
  IMAGES = 'PDP.IMAGES',
  TITLE = 'PDP.TITLE',
  RATING = 'PDP.RATING',
  PRICE = 'PDP.PRICE',
  SHARE = 'PDP.SHARE',
}

export enum ProductTabsOutlets {
  DESCRIPTION = 'PDP.DESCRIPTION',
  SPECIFICATIONS = 'PDP.SPECIFICATIONS',
  REVIEWS = 'PDP.REVIEWS',
  SHIPPING = 'PDP.SHIPPING',
}
