export enum ProductDetailOutlets {
  SUMMARY = 'PDP.SUMMARY',
  TITLE = 'PDP.TITLE',
  RATING = 'PDP.RATING',
  ADDTOCART = 'PDP.ADDTOCART',
  PRICE = 'PDP.PRICE',
  SHARE = 'PDP.SHARE',
  DESCRIPTION = 'PDP.DESCRIPTION',
}
