import {
  ChangeDetectionStrategy,
  Component,
  HostBinding,
  Input,
  isDevMode,
} from '@angular/core';
import { Table } from './table.model';

/**
 * The table component provides a generic DOM structure based on the `dataset` input.
 * The `Table` dataset contains a type, table structure and table data.
 *
 * The table component only supports horizontal table structure.
 *
 * The implementation is fairly "dumb" and only provides the following features:
 * - Use outlet for table headers (`<th>`) and cells (`<td>`).
 * - Localizing table headers, using the `I18nModule`.
 * - Add CSS classes on each cell to
 *
 * Al features are optional.
 *
 * By default, the headers and columns are rendered with an outlet template. The template
 * reference is generated by concatenating the table `type` and table fields.
 * The following snippet shows an outlet generated for a table header, for the table type
 * "cost-center" with field "name":
 *
 * ```
 * <th>
 *   <template cxOutlet="tbl.cost-center.header.name">
 *     [localized label is generated here]
 *   </template>
 * </th>
 * ```
 *
 * Similarly, the `<td>` is generated with the outlet template reference `tbl.cost-center.data.name`.
 *
 * This allows smart components to further customize the table rendering. More over, customers can
 * customize the header and data by using the generated outlets.
 */
@Component({
  selector: 'cx-table',
  templateUrl: './table.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TableComponent {
  @HostBinding('attr.__cx-table-type') tableType: string;

  protected _dataset: Table;
  @Input()
  set dataset(dataset: Table) {
    this._dataset = dataset;
    this.addTableDebugInfo();
  }

  get dataset(): Table {
    return this._dataset;
  }

  /**
   * Returns the configured data value by field.
   * If there's no field available, or no corresponding value, the
   * first value in the data row is returned.
   */
  getDataValue(dataRow: any, field: string, index: number): string {
    return dataRow[field] || Object.values(dataRow)[index];
  }

  /**
   * Generates the table type into the UI in devMode, so that developers
   * can easily get the notion of the table type.
   */
  protected addTableDebugInfo() {
    if (isDevMode) {
      this.tableType = this.dataset?.structure?.type;
    }
  }
}
