export enum ProductDetailOutlets {
  PAGE = 'PDP.PAGE',
  SUMMARY = 'PDP.SUMMARY',
  IMAGES = 'PDP.IMAGES',
  TAB = 'PDP.TAB',
  DESCRIPTION = 'PDP.DESCRIPTION',
  SPECIFICATIONS = 'PDP.SPECIFICATIONS',
  REVIEWS = 'PDP.REVIEWS',
  SHIPPING = 'PDP.SHIPPING'
}

export enum ProductSummaryOutlets {
  TITLE = 'PSUM.TITLE',
  RATING = 'PSUM.RATING',
  ADDTOCART = 'PSUM.ADDTOCART',
  PRICE = 'PSUM.PRICE',
  SHARE = 'PSUM.SHARE'
}
