export enum ProductDetailOutlets {
  PAGE = 'PDP.PAGE',
  TITLE = 'PDP.TITLE',
  SUMMARY = 'PDP.SUMMARY',
  ADDTOCART = 'PDP.ADD_TO_CART',
  IMAGES = 'PDP.IMAGES',
  SHARE = 'PDP.SHARE',
  RATING = 'PDP.RATING',
  TAB = 'PDP.TAB',
  DESCRIPTION = 'PDP.DESCRIPTION',
  SPECIFICATIONS = 'PDP.SPECIFICATIONS',
  REVIEWS = 'PDP.REVIEWS',
  SHIPPING = 'PDP.SHIPPING'
}
