export enum ProductDetailTemplates {
  PAGE = 'PDP_PAGE',
  TITLE = 'PDP_TITLE',
  SUMMARY = 'PDP_SUMMARY',
  ADDTOCART = 'PDP_ADD_TO_CART',
  IMAGES = 'PDP_IMAGES',
  SHARE = 'PDP_SHARE',
  RATING = 'PDP_RATING',
  TAB = 'PDP_TAB',
  DESCRIPTION = 'DESCRIPTION',
  SPECIFICATIONS = 'SPECIFICATIONS',
  REVIEWS = 'REVIEWS',
  SHIPPING = 'SHIPPING'
}
