name: 'Collect E2E Screenshots'
description: 'Collect screenshots from E2E test runs'
inputs:
  test-suite:
    description: 'Test suite name'
    required: true
  container-id:
    description: 'Matrix container identifier'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Upload screenshots
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
      with:
        name: e2e-screenshots-${{ inputs.test-suite }}-container-${{ inputs.container-id }}
        path: projects/storefrontapp-e2e-cypress/cypress/screenshots/
        retention-days: 30
        if-no-files-found: ignore
