name: 'Prevent E2E Retries'
description: 'Forcefully fail build if e2e job is retried'
runs:
  using: 'composite'
  steps:
    - name: Forcefully fail build if e2e job is retried
      uses: actions/github-script@v7
      with:
        script: |
          core.setFailed('Please push a commit to trigger the build. To push an empty commit you can use `git commit --allow-empty -m "Trigger Build"`')
      if: ${{ github.run_attempt > 1 }}
