import { NgModule } from '@angular/core';
import {
  AnonymousConsentsModule,
  AuthModule,
  CostCenterOccModule,
  ExternalRoutesModule,
  ProductModule,
  ProductOccModule,
  provideFeatureToggles,
  UserModule,
  UserOccModule,
} from '@spartacus/core';
import {
  AnonymousConsentManagementBannerModule,
  AnonymousConsentsDialogModule,
  BannerCarouselModule,
  BannerModule,
  BreadcrumbModule,
  CategoryNavigationModule,
  CmsParagraphModule,
  ConsentManagementModule,
  FooterNavigationModule,
  HamburgerMenuModule,
  HomePageEventModule,
  LinkModule,
  LoginRouteModule,
  LogoutModule,
  MyAccountV2Module,
  MyCouponsModule,
  MyInterestsModule,
  NavigationEventModule,
  NavigationModule,
  NotificationPreferenceModule,
  PageTitleModule,
  PaymentMethodsModule,
  PDFModule,
  ProductCarouselModule,
  ProductDetailsPageModule,
  ProductFacetNavigationModule,
  ProductImagesModule,
  ProductIntroModule,
  ProductListingPageModule,
  ProductListModule,
  ProductPageEventModule,
  ProductReferencesModule,
  ProductSummaryModule,
  ProductTabsModule,
  ScrollToTopModule,
  SearchBoxModule,
  SiteContextSelectorModule,
  SiteThemeSwitcherModule,
  StockNotificationModule,
  TabParagraphContainerModule,
  VideoModule,
} from '@spartacus/storefront';
import { AsmCustomer360FeatureModule } from './features/asm/asm-customer360-feature.module';
import { AsmFeatureModule } from './features/asm/asm-feature.module';
import { CartBaseFeatureModule } from './features/cart/cart-base-feature.module';
import { CartImportExportFeatureModule } from './features/cart/cart-import-export-feature.module';
import { CartQuickOrderFeatureModule } from './features/cart/cart-quick-order-feature.module';
import { CartSavedCartFeatureModule } from './features/cart/cart-saved-cart-feature.module';
import { WishListFeatureModule } from './features/cart/wish-list-feature.module';
import { CheckoutFeatureModule } from './features/checkout/checkout-feature.module';
import { OrderFeatureModule } from './features/order/order-feature.module';
import { ProductImageZoomFeatureModule } from './features/product/product-image-zoom-feature.module';
import { ProductVariantsFeatureModule } from './features/product/product-variants-feature.module';
import { SmartEditFeatureModule } from './features/smartedit/smart-edit-feature.module';
import { StoreFinderFeatureModule } from './features/storefinder/store-finder-feature.module';
import { PersonalizationFeatureModule } from './features/tracking/personalization-feature.module';
import { UserFeatureModule } from './features/user/user-feature.module';

@NgModule({
  declarations: [],
  imports: [
    AuthModule.forRoot(),
    LogoutModule,
    LoginRouteModule,
    HamburgerMenuModule,
    SiteContextSelectorModule,
    LinkModule,
    BannerModule,
    CmsParagraphModule,
    TabParagraphContainerModule,
    BannerCarouselModule,
    CategoryNavigationModule,
    NavigationModule,
    FooterNavigationModule,
    BreadcrumbModule,
    ScrollToTopModule,
    PageTitleModule,
    VideoModule,
    PDFModule,
    SiteThemeSwitcherModule,
    UserModule,
    UserOccModule,
    PaymentMethodsModule,
    NotificationPreferenceModule,
    MyInterestsModule,
    MyAccountV2Module,
    StockNotificationModule,
    ConsentManagementModule,
    MyCouponsModule,
    AnonymousConsentsModule.forRoot(),
    AnonymousConsentsDialogModule,
    AnonymousConsentManagementBannerModule,
    ProductModule.forRoot(),
    ProductOccModule,
    ProductDetailsPageModule,
    ProductListingPageModule,
    ProductListModule,
    SearchBoxModule,
    ProductFacetNavigationModule,
    ProductTabsModule,
    ProductCarouselModule,
    ProductReferencesModule,
    ProductImagesModule,
    ProductSummaryModule,
    ProductIntroModule,
    CostCenterOccModule,
    NavigationEventModule,
    HomePageEventModule,
    ProductPageEventModule,
    ExternalRoutesModule.forRoot(),
    UserFeatureModule,
    CartBaseFeatureModule,
    CartSavedCartFeatureModule,
    WishListFeatureModule,
    CartQuickOrderFeatureModule,
    CartImportExportFeatureModule,
    OrderFeatureModule,
    CheckoutFeatureModule,
    PersonalizationFeatureModule,
    StoreFinderFeatureModule,
    AsmFeatureModule,
    AsmCustomer360FeatureModule,
    SmartEditFeatureModule,
    ProductVariantsFeatureModule,
    ProductImageZoomFeatureModule,
  ],
  providers: [
    provideFeatureToggles({
      showDeliveryOptionsTranslation: true,
      formErrorsDescriptiveMessages: true,
      showSearchingCustomerByOrderInASM: true,
      showStyleChangesInASM: true,
      shouldHideAddToCartForUnpurchasableProducts: true,
      useExtractedBillingAddressComponent: true,
      showBillingAddressInDigitalPayments: true,
      showDownloadProposalButton: true,
      searchBoxV2: true,
      trendingSearches: true,
      pdfInvoicesSortByInvoiceDate: true,
      useProductCarouselBatchApi: true,
      productConfiguratorAttributeTypesV2: true,
      propagateErrorsToServer: true,
      ssrStrictErrorHandlingForHttpAndNgrx: true,
      productConfiguratorDeltaRendering: true,
      a11yRequiredAsterisks: true,
      a11yQuantityOrderTabbing: true,
      a11yNavigationUiKeyboardControls: true,
      a11yUseProperTextColorForFutureStockAccordion: true,
      a11yNavMenuExpandStateReadout: true,
      a11yOrderConfirmationHeadingOrder: true,
      a11yStarRating: true,
      a11yViewChangeAssistiveMessage: true,
      a11yPreventHorizontalScroll: true,
      a11yReorderDialog: true,
      a11yPopoverFocus: true,
      a11yPopoverHighContrast: true,
      a11yTabsManualActivation: true,
      a11yScheduleReplenishment: true,
      a11yScrollToTop: true,
      a11ySavedCartsZoom: true,
      a11ySortingOptionsTruncation: true,
      a11yExpandedFocusIndicator: true,
      a11yCheckoutDeliveryFocus: true,
      a11yMobileVisibleFocus: true,
      a11yOrganizationsBanner: true,
      a11yOrganizationListHeadingOrder: true,
      a11yCartImportConfirmationMessage: true,
      a11yAnonymousConsentMessageInDialog: true,
      a11yReplenishmentOrderFieldset: true,
      a11yListOversizedFocus: true,
      a11yStoreFinderOverflow: true,
      a11yMobileFocusOnFirstNavigationItem: true,
      a11yQuickOrderSearchListKeyboardNavigation: true,
      a11yCartSummaryHeadingOrder: true,
      a11ySearchBoxMobileFocus: true,
      a11yFacetKeyboardNavigation: true,
      a11yUnitsListKeyboardControls: true,
      a11yCartItemsLinksStyles: true,
      a11yStyleExternalLinksAsLinks: true,
      a11ySearchboxLabel: true,
      a11yHideSelectBtnForSelectedAddrOrPayment: true,
      a11ySelectLabelWithContextForSelectedAddrOrPayment: true,
      a11yFocusableCarouselControls: true,
      a11yUseTrapTabInsteadOfTrapInDialogs: true,
      cmsGuardsServiceUseGuardsComposer: true,
      cartQuickOrderRemoveListeningToFailEvent: true,
      a11yKeyboardAccessibleZoom: true,
      a11yOrganizationLinkableCells: true,
      a11yVisibleFocusOverflows: true,
      a11yTruncatedTextForResponsiveView: true,
      a11yTruncatedTextStoreFinder: true,
      a11yTruncatedTextUnitLevelOrderHistory: true,
      a11ySemanticPaginationLabel: true,
      a11yPreventCartItemsFormRedundantRecreation: true,
      a11yPreventSRFocusOnHiddenElements: true,
      a11yMyAccountLinkOutline: true,
      a11yCloseProductImageBtnFocus: true,
      a11yNotificationPreferenceFieldset: true,
      a11yImproveContrast: true,
      a11yEmptyWishlistHeading: true,
      a11yScreenReaderBloatFix: true,
      a11yUseButtonsForBtnLinks: true,
      a11yTabComponent: true,
      a11yCarouselArrowKeysNavigation: true,
      a11yPickupOptionsTabs: true,
      a11yNotificationsOnConsentChange: true,
      a11yDisabledCouponAndQuickOrderActionButtonsInsteadOfRequiredFields: true,
      a11yFacetsDialogFocusHandling: true,
      a11yResetFocusAfterNavigating: true,
      headerLayoutForSmallerViewports: true,
      a11yStoreFinderAlerts: true,
      a11yStoreFinderLabel: true,
      a11yFormErrorMuteIcon: true,
      a11yCxMessageFocus: true,
      a11yLinkBtnsToTertiaryBtns: true,
      a11yRepeatedPageTitleFix: true,
      a11yDeliveryModeRadiogroup: true,
      a11yNgSelectOptionsCount: true,
      a11yNgSelectCloseDropdownOnEscape: true,
      a11ySelectImprovementsCustomerTicketingCreateSelectbox: true,
      a11yNgSelectAriaLabelDropdownCustomized: true,
      a11yRepeatedCancelOrderError: true,
      a11yAddedToCartActiveDialog: true,
      a11yNgSelectMobileReadout: true,
      a11yDeliveryMethodFieldset: true,
      a11yShowMoreReviewsBtnFocus: true,
      a11yQuickOrderAriaControls: true,
      a11yRemoveStatusLoadedRole: true,
      a11yDialogsHeading: true,
      a11yDialogTriggerRefocus: true,
      a11yAddToWishlistFocus: true,
      a11ySearchBoxFocusOnEscape: true,
      a11yUpdatingCartNoNarration: true,
      a11yPasswordVisibliltyBtnValueOverflow: true,
      a11yItemCounterFocus: true,
      a11yScrollToReviewByShowReview: true,
      a11yViewHoursButtonIconContrast: true,
      a11yStoreInStockIconContrast: true,
      a11yCheckoutStepsLandmarks: true,
      a11yQTY2Quantity: true,
      a11yImproveButtonsInCardComponent: true,
      a11yMiniCartFocusOnMobile: true,
      a11yWrapReviewOrderInSection: true,
      a11yApprovalProcessWithNoClearable: true,
      a11yPostRegisterSuccessMessage: true,
      a11yDeleteButton2First: true,
      a11yShowLabelOfSelect: true,
      a11yShowDownArrowOnFocusedSelectMenu: true,
      a11yCroppedFocusRing: true,
      a11yTextSpacingAdjustments: true,
      a11yTableHeaderReadout: true,
      a11ySearchboxAssistiveMessage: true,
      updateConsentGivenInOnChanges: true,
      a11yDifferentiateFocusedAndSelected: true,
      a11yQuickOrderSearchBoxRefocusOnClose: true,
      a11yKeyboardFocusInSearchBox: true,
      a11yAddPaddingToCarouselPanel: true,
      a11yNavigationButtonsAriaFixes: true,
      a11yFocusOnCardAfterSelecting: true,
      a11ySearchableDropdownFirstElementFocus: true,
      a11yHideConsentButtonWhenBannerVisible: true,
      a11yRepeatingButtonsUniqueLabels: true,
      a11yHighContrastBorders: true,
      a11yRegionAssociatedHeaders: true,
      occCartNameAndDescriptionInHttpRequestBody: true,
      cmsBottomHeaderSlotUsingFlexStyles: true,
      useSiteThemeService: true,
      enableConsecutiveCharactersPasswordRequirement: true,
      enablePasswordsCannotMatchInPasswordUpdateForm: true,
      allPageMetaResolversEnabledInCsr: true,
      a11yPdpGridArrangement: true,
      a11yHamburgerMenuTrapFocus: true,
      useExtendedMediaComponentConfiguration: true,
      showRealTimeStockInPDP: true,
      a11yScrollToTopPositioning: true,
      enableSecurePasswordValidation: true,
      enableCarouselCategoryProducts: true,
      enableClaimCustomerCouponWithCodeInRequestBody: true,
    }),
  ],
})
export class SpartacusFeaturesModule {}
