on:
  pull_request:
    types: [opened, synchronize, reopened]
name: API extractor
jobs:
  detect_changes:
    name: API extractor - Detect changes
    runs-on: ubuntu-latest
    outputs:
      RUN_CHECKS: ${{ steps.changes.outputs.RUN_CHECKS }}
    steps:
      - uses: actions/checkout@v6
      - name: Detect code changes
        id: changes
        uses: ./.github/actions/detect-changes

  breakingChangeDetectionBot:
    needs: [detect_changes]
    name: Breaking change detection bot
    runs-on: ubuntu-latest
    if: ${{ needs.detect_changes.outputs.RUN_CHECKS == 'true' }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@master
      - name: Breaking change detection bot
        uses: ./.github/api-extractor-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
