on:
  pull_request:
    types: [opened, synchronize, reopened]
name: API extractor
permissions:
  contents: read
  pull-requests: write
  actions: write
jobs:
  detect_changes:
    name: API extractor - Detect changes
    runs-on: ubuntu-latest
    outputs:
      RUN_CHECKS: ${{ steps.detect_code_changes.outputs.RUN_CHECKS }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Detect code changes
        id: detect_code_changes
        uses: ./.github/actions/detect-changes

  breakingChangeDetectionBot:
    needs: [detect_changes]
    name: Breaking change detection bot
    runs-on: ubuntu-latest
    if: ${{ needs.detect_changes.outputs.RUN_CHECKS == 'true' }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@d07a454dad7609a92316b57b23c9ccfd4f59af66 # 0.13.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Breaking change detection bot
        uses: ./.github/api-extractor-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
