on:
  push:
    branches:
      - develop
      - develop-*
      - 'epic/**'
      - release/*
    paths-ignore:
      - '**.md'
      - 'docs/**'
name: Cache libs (dist)
permissions:
  contents: read
  actions: write
jobs:
  cacheBuildedLibs:
    name: Builded libs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      - name: Cache builded libs
        uses: ./.github/cache-builded-libs
