on:
  push:
    branches:
      - develop
      - develop-*
      - 'epic/**'
      - release/*
name: Cache libs (dist)
permissions:
  contents: read
  actions: write
jobs:
  detect_changes:
    name: Cache libs - Detect changes
    runs-on: ubuntu-latest
    outputs:
      RUN_CHECKS: ${{ steps.detect_code_changes.outputs.RUN_CHECKS }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      - name: Detect code changes
        id: detect_code_changes
        uses: ./.github/actions/detect-changes

  cacheBuildedLibs:
    needs: [detect_changes]
    name: Builded libs
    runs-on: ubuntu-latest
    if: ${{ needs.detect_changes.outputs.RUN_CHECKS == 'true' }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      - name: Cache builded libs
        uses: ./.github/cache-builded-libs
