on:
  push:
    branches:
      - develop
      - develop-*
      - 'epic/**'
      - release/*
name: Cache node modules

permissions:
  contents: read
  actions: write

env:
  NODE_VERSION: '20'
  CONTINUUM_REGISTRY_TOKEN: ${{ secrets.CONTINUUM_REGISTRY_TOKEN }}

jobs:
  detect_changes:
    name: Cache node modules - Detect changes
    runs-on: ubuntu-latest
    outputs:
      RUN_CHECKS: ${{ steps.detect_code_changes.outputs.RUN_CHECKS }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Detect code changes
        id: detect_code_changes
        uses: ./.github/actions/detect-changes

  cacheNodeModules:   
    needs: [detect_changes]
    name: Cache node_modules
    runs-on: ubuntu-latest
    if: ${{ needs.detect_changes.outputs.RUN_CHECKS == 'true' }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Installing root dependencies
        run: npm ci
      - name: Installing cypress dependencies
        working-directory: projects/storefrontapp-e2e-cypress
        run: npm ci
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 #v4.3.0
        with:
          path: | 
            node_modules
            projects/storefrontapp-e2e-cypress/node_modules
            ~/.cache/Cypress
          key: nodemodules-${{ github.sha }}
