on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - develop
      - develop-*
      - release/*
      - epic/**
  workflow_dispatch:
    # empty as it is used only to manually trigger the workflow

permissions:
  contents: read
  pull-requests: write
    
env:
  NODE_VERSION: '20'
  NX_BASE: origin/${{ github.event.pull_request.base.ref }}
  NX_HEAD: origin/${{ github.event.pull_request.head.ref }}

concurrency: 
  group: ci-continuous-integration-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: Continuous Integration
jobs:
  detect_changes:
    name: CI - Detect changes
    runs-on: ubuntu-latest
    outputs:
      RUN_CI_CHECKS: ${{ steps.detect_code_changes.outputs.RUN_CHECKS }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Detect code changes
        id: detect_code_changes
        uses: ./.github/actions/detect-changes

  unit_tests:
    needs: [detect_changes]
    name: CI - Unit tests
    runs-on: ubuntu-latest
    if: ${{ needs.detect_changes.outputs.RUN_CI_CHECKS == 'true' }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 #v4.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: | 
            node_modules
            projects/storefrontapp-e2e-cypress/node_modules
            ~/.cache/Cypress
          key: nodemodules-${{ github.event.pull_request.base.sha }}
          restore-keys: nodemodules-${{ github.event.pull_request.base.sha }}
      - name: Package installation
        run: npm ci
      - name: Run unit tests
        run: |
          ci-scripts/unit-tests.sh          
  sonarqube_scan:
    needs: [detect_changes]
    name: CI - SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@c7ee0f9df90b7aa20e8dcf9695dcfe2e7da5b4f2 # v7.2.1
        with:
          args: >
            -Dsonar.qualitygate.wait=true
            -Dsonar.projectKey=composable-storefront
            -Dsonar.typescript.exclusions=**/.github/**
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonar.tools.sap
    if: ${{ github.event_name == 'pull_request' && needs.detect_changes.outputs.RUN_CI_CHECKS == 'true' }}
  linting:
    needs: [detect_changes]
    name: CI - Validations and static code checks
    runs-on: ubuntu-latest
    if: ${{ needs.detect_changes.outputs.RUN_CI_CHECKS == 'true' }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 #v4.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: | 
            node_modules
            projects/storefrontapp-e2e-cypress/node_modules
            ~/.cache/Cypress
          key: nodemodules-${{ github.event.pull_request.base.sha }}
          restore-keys: nodemodules-${{ github.event.pull_request.base.sha }}
      - name: Package installation
        run: npm ci
      - name: Run linting validation
        run: |
          ci-scripts/validate-lint.sh
  check_peer_dependencies:
    needs: [detect_changes]
    name: CI - Check peerDependencies
    runs-on: ubuntu-latest
    if: ${{ needs.detect_changes.outputs.RUN_CI_CHECKS == 'true' }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 #v4.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Run peerDependencies check
        env:
          BASE_REF: ${{ github.event.pull_request.base.ref }}
        run: |
          bash ci-scripts/check-peer-deps.sh "$BASE_REF"
      - name: Collect peer dependency changes
        id: collect-peer-deps
        run: |
          if [ -s peer-deps-result.txt ]; then
            echo "output<<EOF" >> $GITHUB_OUTPUT
            echo "### ❗ peerDependencies changes detected:" >> $GITHUB_OUTPUT
            cat peer-deps-result.txt >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "output=No peerDependencies changes detected" >> $GITHUB_OUTPUT
          fi
      - name: Post PR comment if peerDependencies changed
        if: failure() && github.event.pull_request
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
                const path = 'peer-deps-result.txt';

            if (!fs.existsSync(path)) {
              console.log("No peer-deps result file found. Skipping comment.");
              return;
            }

            const diff = fs.readFileSync(path, 'utf8').trim();
            if (!diff) {
              console.log("peer-deps result file is empty. Skipping comment.");
              return;
            }

            const issue_number = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const botUser = context.actor;

            const commentHeader = "🚨 **PeerDependencies Change Detected** 🚨";

            const body = `
              ${commentHeader}

              Your pull request includes modifications to \`peerDependencies\` in the following file(s):

              \`\`\`diff
              ${diff}
              \`\`\`

              Please note: Changes to peerDependencies are **restricted** and only permitted during **framework update releases**, as they may introduce breaking changes for customer's applications.
              If you believe this change is necessary, please reach out to the Asterix team for further assistance.
              `;

            await github.rest.issues.createComment({
              issue_number,
              owner,
              repo,
              body
            });

  ci_result:
    needs: [unit_tests, sonarqube_scan, linting, check_peer_dependencies]
    name: CI - Result
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Aggregate Required Job Results
        run: |
            exit 1
        if: |
          needs.unit_tests.result == 'failure' || needs.unit_tests.result == 'cancelled' || 
          needs.sonarqube_scan.result == 'failure' || needs.sonarqube_scan.result == 'cancelled' ||
          needs.linting.result == 'failure' || needs.linting.result == 'cancelled'
