on:
  pull_request:
    types: [opened, synchronize, reopened]
name: Config check
jobs:
  configCheck:
    name: Dependencies and tsconfig files
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@master
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: NPM
        run: npm i
      - name: Check configurations
        run: npm run config:check
        env:
          FORCE_COLOR: 2 # Support colors from chalk
