name: E2E vendor tests

on:
  push:
  #schedule:
     #Runs every day at 10:00 (UTC)
   # - cron: "0 10 * * *"
  workflow_dispatch:

env:
  CYPRESS_KEY: ${{ secrets.CYPRESS_KEY }}
  NODE_VERSION: '20'
  CONTINUUM_REGISTRY_TOKEN: ${{ secrets.CONTINUUM_REGISTRY_TOKEN }}

jobs:
  cdc_b2c_e2e_tests:
    name: E2E tests for CDC B2C
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            projects/storefrontapp-e2e-cypress/node_modules
            ~/.cache/Cypress
          key: nodemodules-${{ github.event.pull_request.base.sha }}
          restore-keys: nodemodules-${{ github.event.pull_request.base.sha }}
      - name: Run e2es
        env:
          SPA_ENV: cdc,b2c
          BUILD_NUMBER: ci-build-number-${{ github.event.pull_request.head.sha || github.run_id }}
        run: |
          ci-scripts/e2e-cypress.sh -s vendor:cdc
  cdc_b2b_e2e_tests:
    name: E2E tests for CDC B2B
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            projects/storefrontapp-e2e-cypress/node_modules
            ~/.cache/Cypress
          key: nodemodules-${{ github.event.pull_request.base.sha }}
          restore-keys: nodemodules-${{ github.event.pull_request.base.sha }}
      - name: Run e2es
        env:
          SPA_ENV: cdc,b2b
          BUILD_NUMBER: ci-build-number-${{ github.event.pull_request.head.sha || github.run_id }}
        run: |
          ci-scripts/e2e-cypress.sh -s vendor:cdc-b2b
  cdp_b2c_e2e_tests:
    name: E2E tests for CDP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            projects/storefrontapp-e2e-cypress/node_modules
            ~/.cache/Cypress
          key: nodemodules-${{ github.event.pull_request.base.sha }}
          restore-keys: nodemodules-${{ github.event.pull_request.base.sha }}
      - name: Run e2es
        env:
          SPA_ENV: cdp,b2c
          BUILD_NUMBER: ci-build-number-${{ github.event.pull_request.head.sha || github.run_id }}
        run: |
          ci-scripts/e2e-cypress.sh -s vendor:cdp
  segment_refs_e2e_tests:
    name: E2E tests for segment refs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            projects/storefrontapp-e2e-cypress/node_modules
            ~/.cache/Cypress
          key: nodemodules-${{ github.event.pull_request.base.sha }}
          restore-keys: nodemodules-${{ github.event.pull_request.base.sha }}
      - name: Run e2es
        env:
          SPA_ENV: segment-refs,b2c
          BUILD_NUMBER: ci-build-number-${{ github.event.pull_request.head.sha || github.run_id }}
        run: |
          ci-scripts/e2e-cypress.sh -s vendor:segment-refs
  digital_payments_e2e_tests:
    name: E2E tests for digital payments
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            projects/storefrontapp-e2e-cypress/node_modules
            ~/.cache/Cypress
          key: nodemodules-${{ github.event.pull_request.base.sha }}
          restore-keys: nodemodules-${{ github.event.pull_request.base.sha }}
      - name: Run e2es
        env:
          SPA_ENV: digital-payments,b2c
          BUILD_NUMBER: ci-build-number-${{ github.event.pull_request.head.sha || github.run_id }}
        run: |
          ci-scripts/e2e-cypress.sh -s vendor:digital-payments
  opps_e2e_tests:
    name: E2E tests for opps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            projects/storefrontapp-e2e-cypress/node_modules
            ~/.cache/Cypress
          key: nodemodules-${{ github.event.pull_request.base.sha }}
          restore-keys: nodemodules-${{ github.event.pull_request.base.sha }}
      - name: Run e2es
        env:
          SPA_ENV: opps,b2c
          BUILD_NUMBER: ci-build-number-${{ github.event.pull_request.head.sha || github.run_id }}
        run: |
          ci-scripts/e2e-cypress.sh -s vendor:opps
  s4_service_e2e_tests:
    name: E2E tests for s4 service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            projects/storefrontapp-e2e-cypress/node_modules
            ~/.cache/Cypress
          key: nodemodules-${{ github.event.pull_request.base.sha }}
          restore-keys: nodemodules-${{ github.event.pull_request.base.sha }}
      - name: Run e2es
        env:
          SPA_ENV: s4-service,b2b
          BUILD_NUMBER: ci-build-number-${{ github.event.pull_request.head.sha || github.run_id }}
        run: |
          ci-scripts/e2e-cypress.sh -s vendor:s4-service
  epd_visualization_e2e_tests:
    name: E2E tests for epd visualization
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            projects/storefrontapp-e2e-cypress/node_modules
            ~/.cache/Cypress
          key: nodemodules-${{ github.event.pull_request.base.sha }}
          restore-keys: nodemodules-${{ github.event.pull_request.base.sha }}
      - name: Run e2es
        env:
          SPA_ENV: epd-visualization,b2c
          BUILD_NUMBER: ci-build-number-${{ github.event.pull_request.head.sha || github.run_id }}
        run: |
          ci-scripts/e2e-cypress.sh -s epd-visualization
  cds_e2e_tests:
    name: E2E tests for cds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            projects/storefrontapp-e2e-cypress/node_modules
            ~/.cache/Cypress
          key: nodemodules-${{ github.event.pull_request.base.sha }}
          restore-keys: nodemodules-${{ github.event.pull_request.base.sha }}
      - name: Run e2es
        env:
          SPA_ENV: cds,b2c
          BUILD_NUMBER: ci-build-number-${{ github.event.pull_request.head.sha || github.run_id }}
        run: |
          ci-scripts/e2e-cypress.sh -s cds
  asm_e2e_tests:
    name: E2E tests for asm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            projects/storefrontapp-e2e-cypress/node_modules
            ~/.cache/Cypress
          key: nodemodules-${{ github.event.pull_request.base.sha }}
          restore-keys: nodemodules-${{ github.event.pull_request.base.sha }}
      - name: Run e2es
        env:
          SPA_ENV: asm,b2c
          BUILD_NUMBER: ci-build-number-${{ github.event.pull_request.head.sha || github.run_id }}
        run: |
          ci-scripts/e2e-cypress.sh -s asm
  product_configurator_e2e_tests:
    name: E2E tests for product configurator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            projects/storefrontapp-e2e-cypress/node_modules
            ~/.cache/Cypress
          key: nodemodules-${{ github.event.pull_request.base.sha }}
          restore-keys: nodemodules-${{ github.event.pull_request.base.sha }}
      - name: Run e2es
        env:
          SPA_ENV: b2c
          BUILD_NUMBER: ci-build-number-${{ github.event.pull_request.head.sha || github.run_id }}
        run: |
          ci-scripts/e2e-cypress.sh -s product-configuration
  pdf_invoices_e2e_tests:
    name: E2E tests for pdf invoices
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            projects/storefrontapp-e2e-cypress/node_modules
            ~/.cache/Cypress
          key: nodemodules-${{ github.event.pull_request.base.sha }}
          restore-keys: nodemodules-${{ github.event.pull_request.base.sha }}
      - name: Run e2es
        env:
          SPA_ENV: b2c
          BUILD_NUMBER: ci-build-number-${{ github.event.pull_request.head.sha || github.run_id }}
        run: |
          ci-scripts/e2e-cypress.sh -s vendor:pdf-invoices
  cpq_e2e_tests:
    name: E2E tests for cpq
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            projects/storefrontapp-e2e-cypress/node_modules
            ~/.cache/Cypress
          key: nodemodules-${{ github.event.pull_request.base.sha }}
          restore-keys: nodemodules-${{ github.event.pull_request.base.sha }}
      - name: Run e2es
        env:
          SPA_ENV: b2c
          BUILD_NUMBER: ci-build-number-${{ github.event.pull_request.head.sha || github.run_id }}
        run: |
          ci-scripts/e2e-cypress.sh -s vendor:cpq
  omf_e2e_tests:
    name: E2E tests for omf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            projects/storefrontapp-e2e-cypress/node_modules
            ~/.cache/Cypress
          key: nodemodules-${{ github.event.pull_request.base.sha }}
          restore-keys: nodemodules-${{ github.event.pull_request.base.sha }}
      - name: Run e2es
        env:
          SPA_ENV: b2c
          BUILD_NUMBER: ci-build-number-${{ github.event.pull_request.head.sha || github.run_id }}
        run: |
          ci-scripts/e2e-cypress.sh -s vendor:omf
  opf_e2e_tests:
    name: E2E tests for opf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            projects/storefrontapp-e2e-cypress/node_modules
            ~/.cache/Cypress
          key: nodemodules-${{ github.event.pull_request.base.sha }}
          restore-keys: nodemodules-${{ github.event.pull_request.base.sha }}
      - name: Run e2es
        env:
          SPA_ENV: b2c
          BUILD_NUMBER: ci-build-number-${{ github.event.pull_request.head.sha || github.run_id }}
        run: |
          ci-scripts/e2e-cypress.sh -s vendor:opf
  s4om_e2e_tests:
    name: E2E tests for s4om
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            projects/storefrontapp-e2e-cypress/node_modules
            ~/.cache/Cypress
          key: nodemodules-${{ github.event.pull_request.base.sha }}
          restore-keys: nodemodules-${{ github.event.pull_request.base.sha }}
      - name: Run e2es
        env:
          SPA_ENV: b2c
          BUILD_NUMBER: ci-build-number-${{ github.event.pull_request.head.sha || github.run_id }}
        run: |
          ci-scripts/e2e-cypress.sh -s vendor:s4om
  estimated_delivery_date_e2e_tests:
    name: E2E tests for estimated delivery date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            projects/storefrontapp-e2e-cypress/node_modules
            ~/.cache/Cypress
          key: nodemodules-${{ github.event.pull_request.base.sha }}
          restore-keys: nodemodules-${{ github.event.pull_request.base.sha }}
      - name: Run e2es
        env:
          SPA_ENV: b2c
          BUILD_NUMBER: ci-build-number-${{ github.event.pull_request.head.sha || github.run_id }}
        run: |
          ci-scripts/e2e-cypress.sh -s vendor:estimated-delivery-date
  pickup_in_store_e2e_tests:
    name: E2E tests for pickup in store
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            projects/storefrontapp-e2e-cypress/node_modules
            ~/.cache/Cypress
          key: nodemodules-${{ github.event.pull_request.base.sha }}
          restore-keys: nodemodules-${{ github.event.pull_request.base.sha }}
      - name: Run e2es
        env:
          SPA_ENV: b2c
          BUILD_NUMBER: ci-build-number-${{ github.event.pull_request.head.sha || github.run_id }}
        run: |
          ci-scripts/e2e-cypress.sh -s vendor:pickup-in-store
  requested_delivery_date_e2e_tests:
    name: E2E tests for requested delivery date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            projects/storefrontapp-e2e-cypress/node_modules
            ~/.cache/Cypress
          key: nodemodules-${{ github.event.pull_request.base.sha }}
          restore-keys: nodemodules-${{ github.event.pull_request.base.sha }}
      - name: Run e2es
        env:
          SPA_ENV: b2c
          BUILD_NUMBER: ci-build-number-${{ github.event.pull_request.head.sha || github.run_id }}
        run: |
          ci-scripts/e2e-cypress.sh -s vendor:requested-delivery-date
  build_conclusion:
    needs: [cdc_b2c_e2e_tests, cdc_b2b_e2e_tests, cdp_b2c_e2e_tests, segment_refs_e2e_tests, digital_payments_e2e_tests, opps_e2e_tests, s4_service_e2e_tests, epd_visualization_e2e_tests, cds_e2e_tests, asm_e2e_tests, product_configurator_e2e_tests, pdf_invoices_e2e_tests, cpq_e2e_tests, omf_e2e_tests, opf_e2e_tests, s4om_e2e_tests, estimated_delivery_date_e2e_tests, pickup_in_store_e2e_tests, requested-delivery-date_e2e_tests]
    name: Build Conclusion
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Required build failed
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('Build failed')
        if: |
          needs.cdc_b2c_e2e_tests.result == 'failure' || needs.cdc_b2c_e2e_tests.result == 'cancelled' ||
          needs.cdc_b2b_e2e_tests.result == 'failure' || needs.cdc_b2b_e2e_tests.result == 'cancelled' ||
          needs.cdp_b2c_e2e_tests.result == 'failure' || needs.cdp_b2c_e2e_tests.result == 'cancelled' ||
          needs.segment_refs_e2e_tests.result == 'failure' || needs.segment_refs_e2e_tests.result == 'cancelled' ||
          needs.digital_payments_e2e_tests.result == 'failure' || needs.digital_payments_e2e_tests.result == 'cancelled' ||
          needs.opps_e2e_tests.result == 'failure' || needs.opps_e2e_tests.result == 'cancelled' ||
          needs.s4_service_e2e_tests.result == 'failure' || needs.s4_service_e2e_tests.result == 'cancelled' ||
          needs.epd_visualization_e2e_tests.result == 'failure' || needs.epd_visualization_e2e_tests.result == 'cancelled' ||
          needs.cds_e2e_tests.result == 'failure' || needs.cds_e2e_tests.result == 'cancelled' ||
          needs.asm_e2e_tests.result == 'failure' || needs.asm_e2e_tests.result == 'cancelled' ||
          needs.product_configurator_e2e_tests.result == 'failure' || needs.product_configurator_e2e_tests.result == 'cancelled' ||
          needs.pdf_invoices_e2e_tests.result == 'failure' || needs.pdf_invoices_e2e_tests.result == 'cancelled' ||
          needs.cpq_e2e_tests.result == 'failure' || needs.cpq_e2e_tests.result == 'cancelled' ||
          needs.omf_e2e_tests.result == 'failure' || needs.omf_e2e_tests.result == 'cancelled' ||
          needs.opf_e2e_tests.result == 'failure' || needs.opf_e2e_tests.result == 'cancelled' ||
          needs.s4om_e2e_tests.result == 'failure' || needs.s4om_e2e_tests.result == 'cancelled' ||
          needs.estimated_delivery_date_e2e_tests.result == 'failure' || needs.estimated_delivery_date_e2e_tests.result == 'cancelled' ||
          needs.pickup_in_store_e2e_tests.result == 'failure' || needs.pickup_in_store_e2e_tests.result == 'cancelled' ||
          needs.requested_delivery_date_e2e_tests.result == 'failure' || needs.requested_delivery_date_e2e_tests.result == 'cancelled'
  send_slack_message:
    needs: build_conclusion
    name: Slack message for failed CI build in Spartacus
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - run: |
          echo "Context Info:"
          echo "  Event = ${{ github.event_name }}"
          echo "  Build Result = ${{ needs.build_conclusion.result }}"
          echo "  Branch = ${{ github.ref_name }}"
          echo "  Default branch = ${{ github.event.repository.default_branch }}"
      - name: Notify the slack channel of when build conclusion failed
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
        uses: slackapi/slack-github-action@v1.27.1
        with:
          channel-id: ${{ secrets.SLACK_NOTIFICATION_CHANNEL }}
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":nuclear-bomb: :fireduck: *Vendor E2E Tests Failed*"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Failed build",
                        "emoji": true
                      },
                      "value": "failed_build",
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "What was committed?",
                        "emoji": true
                      },
                      "value": "recent_merged_commit",
                      "url": "${{ github.event.head_commit.url }}"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Build history",
                        "emoji": true
                      },
                      "value": "buid_history",
                      "url": "https://github.com/SAP/spartacus/actions/workflows/e2e-vendor.yml?query=branch%3Adevelop"
                    }
                  ]
                }
              ]
            }
        if: |
          needs.build_conclusion.result == 'failure'

