name: E2E Tests

on:
  push:               

jobs:
  e2e-tests-2:
    name: CI - E2E Tests v2
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run standard E2E
        run: npm run e2e:run

      - name: Run B2B E2E
        run: npm run e2e:run:b2b

      - name: Run SSR E2E
        run: npm run e2e:run:ci:ssr

  send_slack_message:
    needs: build_conclusion
    name: Slack message for failed CI build in Spartacus
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - run: |
          echo "Context Info:"
          echo "  Event = ${{ github.event_name }}"
          echo "  Build Result = ${{ needs.build_conclusion.result }}"
          echo "  Branch = ${{ github.ref_name }}"
          echo "  Default branch = ${{ github.event.repository.default_branch }}"
      - name: Notify the slack channel of when build conclusion failed
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
        uses: slackapi/slack-github-action@v1.27.1
        with:
          channel-id: ${{ secrets.SLACK_NOTIFICATION_CHANNEL }}
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":nuclear-bomb: :fireduck: *Broken build on ${{ github.ref_name }}*"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Failed build",
                        "emoji": true
                      },
                      "value": "failed_build",
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "What was committed?",
                        "emoji": true
                      },
                      "value": "recent_merged_commit",
                      "url": "${{ github.event.head_commit.url }}"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Build history",
                        "emoji": true
                      },
                      "value": "buid_history",
                      "url": "https://github.com/SAP/spartacus/actions/workflows/ci.yml?query=branch%3Adevelop"
                    }
                  ]
                }
              ]
            }
        if: |
          needs.build_conclusion.result == 'failure' &&
          github.event_name == 'push' &&
          github.ref_name == github.event.repository.default_branch
  ci_result:
    needs: [e2e-tests-2]
    name: CI - Result
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Aggregate Required Job Results
        run: |
            exit 1
        if: |
          needs.e2e-tests-2.result == 'failure' || needs.e2e-tests-2.result == 'cancelled'

