name: E2E Tests

on:
  push:

jobs:
  run-all-e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: [
          'e2e:run',
          'e2e:run:b2b',
          'e2e:run:ci:ssr',
          'e2e:run:ci:core',
          'e2e:run:ci:asm'
        ]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install main repo dependencies
        run: npm ci

      - name: Install Cypress in subfolder
        run: npm ci --prefix ./projects/storefrontapp-e2e-cypress

      - name: Run E2E script
        run: npm run ${{ matrix.script }}

  aggregator:
    needs: [run-all-e2e]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Aggregated result
        run: |
          echo "All parallel E2E jobs completed!"
          if [ '${{ needs.run-all-e2e.result }}' = 'failure' ]; then
            echo "One or more E2E scripts failed."
            exit 1
          else
            echo "All E2E scripts succeeded."
  send_slack_message:
    needs: [run-all-e2e]
    name: Slack message for failed CI build in Spartacus
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - run: |
          echo "Context Info:"
          echo "  Event = ${{ github.event_name }}"
          echo "  Build Result = ${{ needs.run-all-e2e.result }}"
          echo "  Branch = ${{ github.ref_name }}"
          echo "  Default branch = ${{ github.event.repository.default_branch }}"
      - name: Notify the slack channel of when build conclusion failed
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
        uses: slackapi/slack-github-action@v1.27.1
        with:
          channel-id: ${{ secrets.SLACK_NOTIFICATION_CHANNEL }}
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":nuclear-bomb: :fireduck: *Broken build on ${{ github.ref_name }}*"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Failed build",
                        "emoji": true
                      },
                      "value": "failed_build",
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "What was committed?",
                        "emoji": true
                      },
                      "value": "recent_merged_commit",
                      "url": "${{ github.event.head_commit.url }}"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Build history",
                        "emoji": true
                      },
                      "value": "buid_history",
                      "url": "https://github.com/SAP/spartacus/actions/workflows/ci.yml?query=branch%3Adevelop"
                    }
                  ]
                }
              ]
            }
        if: >
          (needs.run-all-e2e.result == 'failure') &&
          (github.event_name == 'push') &&
          (github.ref_name == github.event.repository.default_branch)

  ci_result:
    needs: [run-all-e2e]
    name: CI - Result
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Aggregate Required Job Results
        run: exit 1
        if: >
          needs.run-all-e2e.result == 'failure' ||
          needs.run-all-e2e.result == 'cancelled'
