on:
  push:
    branches:
      - 'release/4.**'
      - 'epic/**'
      - 'develop'
      - 'develop-*'

name: Installation

permissions:
  contents: read
  actions: write

jobs:
  detect_changes:
    name: Installation - Detect changes
    runs-on: ubuntu-latest
    outputs:
      RUN_CHECKS: ${{ steps.detect_code_changes.outputs.RUN_CHECKS }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      - name: Detect code changes
        id: detect_code_changes
        uses: ./.github/actions/detect-changes

  install:
    needs: [detect_changes]
    name: Build libs and install
    environment: dev
    runs-on: ubuntu-latest
    if: ${{ needs.detect_changes.outputs.RUN_CHECKS == 'true' }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa #0.12.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 #v4.4.0
        with:
          node-version: '20'
      - name: NPM
        run: npm ci
        env:
          FORCE_COLOR: 2 # Support colors from chalk
      - name: run installation script
        run: cd ./scripts/install && ./run.sh install && ./run.sh start
