on:
  pull_request:
    types: [ready_for_review]
    branches:
      - develop
      - develop-*
      - release/*

  workflow_dispatch:
    # empty as it is used only to manually trigger the workflow
env:
  CYPRESS_KEY: ${{ secrets.CYPRESS_KEY }}
  NODE_VERSION: '20'

concurrency: 
  group: lighthouse-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: Lighthouse
jobs:
  detect_changes:
    name: Lighthouse - Detect changes
    runs-on: ubuntu-latest
    outputs:
      RUN_CHECKS: ${{ steps.changes.outputs.RUN_CHECKS }}
    steps:
      - uses: actions/checkout@v6
      - name: Detect code changes
        id: changes
        uses: ./.github/actions/detect-changes

  lighthouse:
    needs: [detect_changes]
    name: Lighthouse score validation
    runs-on: ubuntu-latest
    if: ${{ needs.detect_changes.outputs.RUN_CHECKS == 'true' }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: | 
            node_modules
            projects/storefrontapp-e2e-cypress/node_modules
            ~/.cache/Cypress
          key: nodemodules-${{ github.event.pull_request.base.sha }}
          restore-keys: nodemodules-${{ github.event.pull_request.base.sha }}
      - name: Package installation
        run: npm ci
      - name: Run lighthouse score validation
        run: |
          ci-scripts/lhci.sh
