on:
  pull_request:
    types: [opened, synchronize]

name: Add license header to files

permissions:
  contents: write
  pull-requests: write

jobs:
  detect_changes:
    name: Add license - Detect changes
    runs-on: ubuntu-latest
    outputs:
      RUN_CHECKS: ${{ steps.detect_code_changes.outputs.RUN_CHECKS }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Detect code changes
        id: detect_code_changes
        uses: ./.github/actions/detect-changes

  add_license_header:
    needs: [detect_changes]
    name: Add license header to files
    if: ${{ needs.detect_changes.outputs.RUN_CHECKS == 'true' && github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.14'
      - name: Download reuse tool
        run: pip3 install --user -r ci-scripts/requirements.txt
      - name: Setup git config
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Adding license header to files
        run: ci-scripts/prepend-license.sh
      - name: push added headers
        env:
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: |
          git pull origin "$HEAD_REF"

          if [ -z $(git status --porcelain) ];
          then
              echo "No files to commit"
          else
              git commit -am "Add license header"
              git push
          fi
